<?php 
$section="terminos-condiciones";
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Mi NuNú | Términos y condiciones</title>

    <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="css/uikit.min.css" />
      
    <link href="css/main.css" rel="stylesheet"/>      
    <?php include ('analytics.php') ?>
  </head>
  <body>
  	<?php include ('header.php') ?>
    <div class="container">
        <h1 class="morado grande center">Términos y condiciones</h1>
        <p>Servicios de Cuidado y Educativos MiNuNú Sa de C.V.., se complace en poner a su disposición los Servicios que ofrece, según dicho término se define a continuación, de conformidad con los siguientes Términos y Condiciones que regulan el uso de (i) minunu.mx (en adelante el “Sitio Web”) y las aplicaciones móviles del mismo nombre que puedan ser descargadas a través de android, iOS o cualquier otro sistema (cada una, una “Aplicación”), independientemente de los medios de acceso a ellos, tales como computadoras o dispositivos móviles (teléfonos inteligentes y tabletas); (ii) el contenido de MiNuNú que aparezca en sitios Web de terceros y redes sociales y (iii) a los Usuarios del Sitio Web, de las Aplicaciones o de los Servicios (indistintamente los “Términos y Condiciones” o el “Contrato”).</p>
        <p>Estos Términos y Condiciones constituyen un acuerdo vinculante entre usted y Servicios de Cuidado y Educativos MiNuNú S.A. de C.V.. (la "Compañía," "MiNuNú," "Nosotros,", o "Nuestro") y se consideran aceptados por su parte cada vez que usted acceda al Sitio Web, a las Aplicaciones o solicite cualquiera de los Servicios ofrecidos por Nosotros, en la versión publicada por MiNuNú en el momento mismo en el que el Usted acceda al Sitio Web o a la aplicación, según sea el caso. Cualquier modificación a los presentes Términos y Condiciones será realizada por MiNuNú, cuando así lo considere apropiado, siendo exclusiva responsabilidad del Usuario asegurarse de tomar conocimiento de tales modificaciones.</p>
        <p>MiNuNú es una plataforma o aplicación para dispositivos móviles y sitios web que facilita el contacto entre personas que requieren servicios niñeras (“Cuidado de niños”) y las personas que ofrecen dichos servicios y la contratación de dichos servicios entre ellos (los “Servicios”). MiNuNú funge exclusivamente como un enlace o intermediario y en ningún momento deberá ser considerada como una empresa que presta servicios del cuidado de niños.</p>
        <h3>I. Reglas Generales De Uso</h3>
        <ol>
            <li>La información, consejos, conceptos y opiniones publicadas en el Sitio Web o en la Aplicación no necesariamente reflejan la posición de MiNuNú ni de sus empleados, directores o accionistas. Por lo anterior, MiNuNú no se hace responsable por la información, consejos y opiniones que se emitan en el Sitio Web o en la Aplicación.</li>
            <li>MiNuNú se reserva el derecho de bloquear el acceso o remover en forma parcial o total, toda información, comunicación o material que a su exclusivo juicio pueda resultar: (i) abusivo, difamatorio, obsceno, ofensivo (ii) fraudulento, artificioso o engañoso, (iii) violatorio de derechos de autor, marcas, confidencialidad, secretos industriales o cualquier derecho de propiedad intelectual de un tercero, o (iv) de cualquier forma contravenga lo establecido en los presentes Términos y Condiciones.</li>
        </ol>
        <h3>II. Plataforma MiNuNú, Funcionamiento de la Aplicación y Solicitud del Servicio</h3>
        <p>Plataforma MiNuNú. MiNuNú es una plataforma para conectar a personas que buscan servicios para el cuidado de niños (cada uno un “Cliente”) y a prestadores de servicios independientes en el cuidado de niños que forman parte de la red de MiNuNú (cada una una “NuNú” y de manera conjunta con el Cliente los “Usuarios”) que pueden estar disponibles para realizar dichas tareas del cuidado de niños. La Compañía revisa los antecedentes de cada NuNú a través de servicios de verificación de antecedentes de terceros; sin embargo, la Compañía no garantiza ni garantizará o hace o hará ningún tipo de representación con respecto a la fiabilidad, la calidad o la idoneidad de dichos proveedores en el cuidado de niños. La Compañía no será responsable, en la medida permitida por la ley aplicable, por cualquier reclamación daño o perjuicio que surja en relación con el uso del Sitio Web o de la Aplicación entre un Cliente y una NuNú, igualmente, la Compañía no será responsable de la conducta de cualquier Usuario de la Aplicación o del Sitio Web.</p>
        <h3>Funcionamiento de la Aplicación</h3>
        <ol>
            <li>Usted, el Cliente solicita un Servicio en el cuidado de niños por medio del Sitio Web o la Aplicación. Para ello deberá proporcionar datos fidedignos del lugar en donde se prestará el Servicio del cuidado de niños, así como sus datos personales para identificarlo, y datos de pago para que MiNuNú proceda al cobro del servicio por cuenta de la NuNú.</li>
            <li>Aliada se reserva el derecho de bloquear el acceso o remover en forma parcial o total, toda información, comunicación o material que a su exclusivo juicio pueda resultar: (i) abusivo, difamatorio, obsceno, ofensivo (ii) fraudulento, artificioso o engañoso, (iii) violatorio de derechos de autor, marcas, confidencialidad, secretos industriales o cualquier derecho de propiedad intelectual de un tercero, o (iv) de cualquier forma contravenga lo establecido en los presentes Términos y Condiciones.</li>
            <li>MiNuNú transmitirá los datos personales y la ubicación del Cliente a su red de NuNús para realizar el servicio así como cualquier solicitud especial o comentario hecho por el Cliente.</li>
            <li>MiNuNú confirmará el servicio y proporcionará al Cliente los datos de identificación de la NuNú.</li>
            <li>La NuNú se presentará en el domicilio y hora indicada por el Cliente. Cualquier cambio de hora y/o domicilio deberá ser notificado por el Cliente a través del Sitio Web o Aplicación cuando menos con 12 horas de anticipación al servicio en el cuidado de niños originalmente programado.</li>
            <li>Los Clientes podrá proporcionar a la Compañía retroalimentación sobre el Servicio en el cuidado de niños, incluyendo fallas o errores en relación con dicho servicio. Dicha información podrá ser utilizada por MiNuNú para mejorar y perfeccionar los Servicios, en este sentido, los Usuarios otorgan a la Compañía el uso no exclusivo e irrevocable libre de regalías para usar, reproducir, divulgar, distribuir, modificar y explotar dichos comentarios sin restricción alguna.</li>
            <li>Cancelación del Servicio MiNuNú. Si Usted desea cancelar el Servicio en el cuidado de niños programado, se requiere un aviso de cancelación con cuando menos 5 horas de anticipación al servicio originalmente programado. La notificación deberá ser hecha a través del perfil de cada Usuario o a través de un correo electrónico dirigido a <a href="mailto:info@minunu.mx">info@minunu.mx</a>. MiNuNú se reserva el derecho de cobrar una comisión de $200 pesos para cubrir los gastos administrativos resultantes de la cancelación del servicio. En caso que el Cliente no cancele el servicio y este no pueda ser prestado por causas no imputables a la NuNú o a Nosotros, se cobrará la totalidad de las horas reservadas.</li>
        </ol>
        <h3>III. Obligaciones de los Clientes</h3>
        <p>Las obligaciones del Cliente, son las que se listan a continuación de manera enunciativa pero no limitativa: (i) cubrir el costo del Servicio, (ii) proveer datos verídicos como, nombre, datos de contacto y ubicación donde se llevará a cabo el Servicio así como la existencia de cualquier preferencia o especificación para que la NuNú pueda llevar a cabo el Servicio de manera puntual y eficiente, (iii) no utilizar MiNuNú con fines ilícitos, (iv) sacar en paz y a salvo a la NuNú en caso de incumplir con los términos de servicio e indemnizar a la NuNú por cualquier acción legal que resulte en su contra, (v) contar con la computadora o dispositivo móvil que cumplan con las características y requisitos técnicos para acceder y utilizar la Aplicación, incluyendo la conexión a Internet, (vi) preservar de manera confidencial los datos de la NuNú y no revelarlos ni darles tratamiento no autorizado por la NuNú, y (vii) no utilizar el Sitio Web para exhibir, transmitir, distribuir o vincular cualquier material que sea falso o engañoso, discriminatorio, difamatorio, ofensivo u obsceno o que pueda incitar a discriminación, odio o violencia contra una persona o grupo de personas a causa de su origen o pertenencia a un grupo étnico, raza o religión, a causa de su género o orientación sexual, (viii) asumir todo el riesgo y responsabilidad por el incumplimiento de estas obligaciones.</p>
        <h3>IV. Derechos de Autor y Propiedad Industrial</h3>
        <p>MiNuNú sus logotipos y todo el material que aparece en el Sitio Web y la Aplicación, son marcas, nombres de dominio y nombres comerciales propiedad de MiNuNú protegidos por tratados internacionales y leyes federales y locales en materia de propiedad intelectual y derechos de autor. Los derechos de autor sobre el contenido, organización, recopilación, información, logotipos, fotografías, imágenes, vídeos, programas, aplicaciones, o en general cualquier información contenida o publicada en el Sitio Web o en las Aplicaciones se encuentra debidamente protegida de conformidad con la legislación aplicable en materia de propiedad intelectual.</p>
        <p>Se prohibe expresamente al Usuario a modificar, alterar o suprimir, ya sea en forma total o parcial, los avisos, marcas, nombres comerciales, señas, anuncios, logotipos o en general cualquier indicación que se refiere a la propiedad de información contenida en el Sitio Web. El Usuario se obliga a no modificar, reproducir, copiar, rediseñar, descompilar, adaptar, traducir, preparar trabajos derivados de la Aplicación o del Sitio Web o utilizar la Aplicación para desarrollar cualquier software u otros materiales basados en los mismos.</p>
        <h3>V. Condiciones del Pago</h3>
        <p>Cualquier cargo hecho por la Compañía será exigible inmediatamente después de concluir el servicio en el cuidado de niños y no será reembolsable. Esta Política de no reembolso será aplicable en todo momento, independientemente de su decisión de suspender el uso del Sitio Web, la Aplicación o el Servicio. En caso de que el Cliente no esté conforme con los Servicios realizados podrá contactar al personal de MiNuNú quien podrá ofrecerle asistencia a través de los teléfonos que para tal efecto se publiquen en el Sitio Web.</p>
        <p>La Compañía podrá, discrecionalmente, hacer ofertas o promocionales con diferentes características y diferentes tasas a cualquiera de los Clientes. Estas ofertas o promocionales, a menos que se le haga a Usted, no tendrá influencia alguna en su oferta. MiNuNú puede cambiar los precios por el Servicio cuando lo considere necesario. Sugerimos revisar periódicamente el Sitio Web con el fin de revisar el precio de los Servicios y cualquier modificación que los mismos pudieren sufrir.</p>
        <h3>VI. Deslinde de Responsabilidad</h3>
        <p>El Usuario está de acuerdo que el uso del Sitio Web o de la Aplicación se realiza bajo su propio riesgo. La Compañía no hace ningún tipo de representación ni otorga ningún tipo de garantía en cuanto a la confiabilidad, puntualidad, calidad, idoneidad, disponibilidad, exactitud o totalidad de los Servicios o del Sitio Web y la Aplicación. MiNuNú no garantiza que (i) el uso del Servicio será seguro, oportuno, ininterrumpido o libre de errores (ii) que el Servicio o el software del Sitio Web o la Aplicación cumplirá con sus necesidades o expectativas, (iii) que la calidad de cualquier producto, Servicio, información u otro material obtenido por usted a través del Sitio Web, Aplicación o Servicio (incluyendo cualquier servicio en el cuidado de niños) cumplirá al cien por ciento los requerimientos del Cliente, sus necesidades o expectativas, (iv) que el Sitio Web o la Aplicación estén libres de virus u otros componentes dañinos. El Software del Sitio Web y de la Aplicación así como los Servicio que se ofrecen en MiNuNú se preven sobre una base “Tal Cual” y “Según sean disponibles”.</p>
        <p>MiNuNú no asume responsabilidad alguna por los daños y perjuicios de cualquier naturaleza que pudieran derivarse de la utilización de los Servicios y de los contenidos por parte de los Usuarios que puedan derivarse de la falta de veracidad, exhaustividad o autenticidad de la información que los Usuarios proporcionan, incluyendo pero no limitado a los daños y perjuicios que puedan derivarse de la suplantación de la personalidad de un tercero efectuada por un usuario en cualquier clase de comunicación realizada a través del Sitio Web o la Aplicación.
            MiNuNú no asume ningún tipo de responsabilidad por los servicios de limpieza prestados por proveedores independientes y ajenos a MiNuNú. Así mismo, MiNuNú no será responsable, bajo ninguna circunstancia de cualquier daño o perjuicio, directo o indirecto, causado en virtud de los Servicios contratados y facilitados a través del Sitio Web o de la Aplicación.</p>
        <h3>VII. Cancelación de Cuenta</h3>
        <p>Los Usuarios podrán en el momento que así lo deseen, cancelar su cuenta, en cuyo momento Aliada garantiza eliminar toda la información de dicho Usuario contenida en su cuenta. El proceso y ejercicio de Derechos ARCO está regulado por el Aviso de Privacidad y la Ley Federal de Protección de Datos Personales. No obstante lo anterior, MiNuNú se reserva el derecho y sin necesidad de aviso previo, de cancelar o suspender el derecho de cualquier Usuario de utilizar los Servicios, y bloquear e impedir su acceso y el uso de los Servicios.</p>
        <h3>VIII. Modificaciones a los presentes Términos y Condiciones</h3>
        <p>MiNuNú se reserva el derecho de modificar en cualquier momento que considere oportuno el contenido de estos Términos y Condiciones pudiendo adicionar provisiones relativas a áreas específicas o nuevos Servicios que en un futuro MiNuNú proporcione a través del Sitio Web o de las Aplicaciones, los cuales serán publicadas en el Sitio Web para su lectura y aceptación. Dichas modificaciones formarán parte integrante del presente contrato para todos los efectos legales a que haya lugar. Es responsabilidad de los Usuarios verificar de tiempo en tiempo los presentes Términos y Condiciones para verificar el contenido de los mismos incluyendo cualquier cambio o modificación.</p>
        <h3>IX. Indemnización</h3>
        <p>Al hacer uso del Sitio Web, Aplicaciones y Servicios de MiNuNú, el Usuario consiente en indemnizar a la MiNuNú, sus Afiliadas, accionistas, proveedores, vendedores y asesores de cualquier acción, demanda o reclamación (incluyendo honorarios de abogados y costos judiciales) derivadas de cualquier incumplimiento al presente Contrato por parte del Usuario.</p>
        <h3>X. Limitación de Responsabilidad</h3>
        <p>MiNuNú no será responsable frente a usted ni frente a terceros por la no prestación de un Servicio pactado por una NuNú. En ningún caso y bajo ninguna circunstancia, MiNuNú, sus directores, empleados, agentes o accionistas serán responsables por los daños o perjuicios de cualquier tipo que surjan o de alguna manera se relacionen con el uso o imposibilidad de usar el Servicio, el Sitio Web o la Aplicación, incluyendo sin limitación los daños provocados por la confianza depositada en el Usuario en cualquier información obtenida de MiNuNú, o como resultado de errores, omisiones, interrupciones, eliminación de archivos o correo electrónico, errores, defectos, virus, retrasos en la operación o transmisión o cualquier fallo de funcionamiento, sea éste ocasionado por desastres naturales, fallo de comunicaciones, robo, destrucción o acceso no autorizado a los registros de la Compañía. En ningún caso, la responsabilidad MiNuNú, derivada de un contrato, garantía, responsabilidad objetiva o de otro tipo, que surja en relación con el uso o imposibilidad de uso de los Servicios podrá superar la compensación que se pague en su caso a MiNuNú por el acceso o el uso de los Servicios.</p>
        <h3>XI. Legislación Aplicable y Jurisdicción</h3>
        <p>El presente Contrato se regirá e interpretará de conformidad con las leyes de México, independientemente de las disposiciones relacionadas con conflictos de leyes. Cualquier procedimiento de carácter legal que se derive o se relacione con este Contrato será dirimido en los tribunales competentes de la Ciudad de México, México. Las partes del presente Contrato expresamente renuncian a cualquier otra jurisdicción que pudiera corresponderles en razón de su domicilio presente o futuro o por cualquier otra razón.</p>

        <a href="ordenar" class="boton-arcoiris">Pide tu <strong>NuNú</strong></a>
        <div class="clear"></div>
    </div> 
    <?php include ('footer.php') ?>
    <?php require_once("side-nav.php"); ?>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/uikit.min.js"></script>
  </body>
</html>